version: "3"
services:
   redis:
     image: redis:alpine
     command: redis-server --requirepass newPlace123 --port 6379
     container_name: redis_boot
     hostname: redis_boot
     ports: 
        - 6379:6379
     restart: always
   springbootapp:
      container_name: web_server
      build: .
      ports:
         - 8080:8080
      depends_on: 
         - redis
      restart: always